name: Deploy DAG to Cloud Composer

on:
  push:
    branches:
      - main  # Trigger on push to main branch
    paths:
      - "dags/**"

jobs:
  deploy:
    name: Deploy DAG to Composer
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate with GCP
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project long-perception-447114-s0

    - name: Deploy DAG to Composer
      run: |
        gcloud composer environments storage dags import \
          --environment=composer-dev \
          --location=us-central1 \
          --source=dags/gcs_to_bq_dag.py

    - name: Restart Composer to Apply Changes
      run: |
        gcloud composer environments restart \
          --environment=composer-dev \
          --location=us-central1
