name: Prod - Deploy to Production

on:
  push:
    branches:
      - main  # Runs only when pushing to 'main'
  workflow_dispatch:

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Production (Cloud Storage)
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: print_numbers.py
          destination: gcp-pandas-buc1  # Use a separate prod bucket
