name: Run Python Script and Upload to GCS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run Python Script
        run: python print_numbers.py

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Upload Python Script to GCS
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: print_numbers.py
          destination: gs://gcp-pandas-buc1
