name: Test - Deploy to Staging

on:
  push:
    branches:
      - test  # Runs only when pushing to 'test'
  workflow_dispatch:

jobs:
  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to Staging (Cloud Storage)
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: print_numbers.py
          destination:  gcp-pandas-buc1  # Use a separate test bucket
